[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.9.0-dev1"
version_files = ["pyproject.toml", "src/__version__.py", "setup.py"]
update_changelog_on_bump = true
major_version_zero = true
