print("this is a test")
print("test --changelog")
print("test --check-consistency")
print("increment tag")
print("fixed changelog")
print("test pre-release")
print("sandbox test")
print("test increment dev release")
print("upload just one tag..")